--
-- PostgreSQL database dump
--

\restrict acN4P7FGBDXAt3akgJ8A5ZPYc9ZDzYS1q3IDDmNGbsZY8ZqDrgliC1wWMbvBefq

-- Dumped from database version 16.10 (Debian 16.10-1.pgdg13+1)
-- Dumped by pg_dump version 16.10 (Debian 16.10-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: categoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categoria (
    id bigint NOT NULL,
    nombre character varying(255)
);


ALTER TABLE public.categoria OWNER TO postgres;

--
-- Name: categoria_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categoria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cliente; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cliente (
    id bigint NOT NULL,
    correo character varying(255),
    nombre character varying(255)
);


ALTER TABLE public.cliente OWNER TO postgres;

--
-- Name: cliente_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cliente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cliente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: empresa; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.empresa (
    direccion character varying(255),
    nit character varying(255) NOT NULL,
    nombre character varying(255),
    telefono character varying(255)
);


ALTER TABLE public.empresa OWNER TO postgres;

--
-- Name: orden; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orden (
    fecha date,
    cliente_id bigint,
    id bigint NOT NULL
);


ALTER TABLE public.orden OWNER TO postgres;

--
-- Name: orden_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orden ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orden_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orden_producto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orden_producto (
    orden_id bigint NOT NULL,
    producto_id bigint NOT NULL
);


ALTER TABLE public.orden_producto OWNER TO postgres;

--
-- Name: producto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.producto (
    precio numeric(38,2),
    id bigint NOT NULL,
    caracteristicas character varying(255),
    codigo character varying(255),
    empresa_nit character varying(255),
    nombre character varying(255)
);


ALTER TABLE public.producto OWNER TO postgres;

--
-- Name: producto_categoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.producto_categoria (
    categoria_id bigint NOT NULL,
    producto_id bigint NOT NULL
);


ALTER TABLE public.producto_categoria OWNER TO postgres;

--
-- Name: producto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.producto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.producto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    correo character varying(255),
    password character varying(255),
    role character varying(255)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: categoria; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categoria (id, nombre) FROM stdin;
1	Tecnología
\.


--
-- Data for Name: cliente; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cliente (id, correo, nombre) FROM stdin;
3	diego@example.com	Diego Galindo
\.


--
-- Data for Name: empresa; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.empresa (direccion, nit, nombre, telefono) FROM stdin;
Calle 45 #12	123	TechCorp	555-0000
Cra 10 #20-30	123451	Tech SAna	3001234567
Cra 10 #20-30	12345143	Tech SAnaf	3001234567
Cra 10 #20-31	123456	Tech SAn	3001234567
\.


--
-- Data for Name: orden; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orden (fecha, cliente_id, id) FROM stdin;
2025-10-28	3	2
\.


--
-- Data for Name: orden_producto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orden_producto (orden_id, producto_id) FROM stdin;
2	1
\.


--
-- Data for Name: producto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.producto (precio, id, caracteristicas, codigo, empresa_nit, nombre) FROM stdin;
1500.00	1	16GB RAM, SSD	P001	123	Laptop
4800.50	2	Core i7, 16GB RAM	P002	123	Laptop PHP XPS
4800.50	3	Core i7, 16GB RAM	P003	123451	PC PHP XPS
1.00	4	Black, earaser, Portable and Lightweight	5675	123456	Pencil
\.


--
-- Data for Name: producto_categoria; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.producto_categoria (categoria_id, producto_id) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, correo, password, role) FROM stdin;
1	admin@example.com	$2a$10$NPvhZWAZ93/BObGSTRv6M.WNaGQukql.HPVH1I3ZbOeAe9/qhbkaa	ADMIN
2	prueba@example.com	$2a$10$eQr842h0Q5qAWt1sm0gpdOVOL2OcyyT2fyIohaVGVmKgzrC9VDaHS	EXTERNO
3	prueba1@example.com	$2a$10$Gy7bsER9tCKZxtA5pSf0pOa8bMJcjt0nK.zNfYnVwnq6.CmmpO9d6	ADMIN
\.


--
-- Name: categoria_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categoria_id_seq', 1, true);


--
-- Name: cliente_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cliente_id_seq', 3, true);


--
-- Name: orden_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orden_id_seq', 2, true);


--
-- Name: producto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.producto_id_seq', 4, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 3, true);


--
-- Name: categoria categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categoria
    ADD CONSTRAINT categoria_pkey PRIMARY KEY (id);


--
-- Name: cliente cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_pkey PRIMARY KEY (id);


--
-- Name: empresa empresa_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empresa
    ADD CONSTRAINT empresa_pkey PRIMARY KEY (nit);


--
-- Name: orden orden_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orden
    ADD CONSTRAINT orden_pkey PRIMARY KEY (id);


--
-- Name: producto producto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT producto_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: orden_producto fkfwpg7qmnlgl6w8vltk79030da; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orden_producto
    ADD CONSTRAINT fkfwpg7qmnlgl6w8vltk79030da FOREIGN KEY (orden_id) REFERENCES public.orden(id);


--
-- Name: producto_categoria fkh5teore15e6b0uytoftnh3qnd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto_categoria
    ADD CONSTRAINT fkh5teore15e6b0uytoftnh3qnd FOREIGN KEY (producto_id) REFERENCES public.producto(id);


--
-- Name: orden fkijfuuiwohsilb5l5qcsv6qsdg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orden
    ADD CONSTRAINT fkijfuuiwohsilb5l5qcsv6qsdg FOREIGN KEY (cliente_id) REFERENCES public.cliente(id);


--
-- Name: producto_categoria fkioqw5isra2i5o5qybtege3sgt; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto_categoria
    ADD CONSTRAINT fkioqw5isra2i5o5qybtege3sgt FOREIGN KEY (categoria_id) REFERENCES public.categoria(id);


--
-- Name: orden_producto fkl1uaeyo2ksdiw0ls68ckwptlc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orden_producto
    ADD CONSTRAINT fkl1uaeyo2ksdiw0ls68ckwptlc FOREIGN KEY (producto_id) REFERENCES public.producto(id);


--
-- Name: producto fkospk1uh9ip5vybw3se3nr6t2g; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT fkospk1uh9ip5vybw3se3nr6t2g FOREIGN KEY (empresa_nit) REFERENCES public.empresa(nit);


--
-- PostgreSQL database dump complete
--

\unrestrict acN4P7FGBDXAt3akgJ8A5ZPYc9ZDzYS1q3IDDmNGbsZY8ZqDrgliC1wWMbvBefq

